# Octave ![octave](https://www.gnu.org/software/octave/img/octave-logo.svg)

- Octave/MatLab is considered the most basic proto typing language for Implementing advanced mathematical algorithms
- Octave/MatLab both these have similar syntax but matlab is more advanced and a bit costly, whereas octave is free


another best progrramming for statistcal implemetation is R 


this jupyter notebook documentation is a quick refernce to the octave basic syntax, that you need to implement machine learning algorithms

## basic Syntax

In [1]:
# oferatrs
3 + 3

4 ^ 3

4 /3 #give's the true division 

# all arthematics operator are as usual

ans =  6
ans =  64
ans =  1.3333


In [2]:
# logical operators
1 && 1 %and

1 || 0 % or

xor(1, 1) %xor

ans = 1
ans = 1
ans = 0


In [3]:
9 == 3 % ezuality 

1 ~= 3 % not equality


ans = 0
ans = 1


string

In [4]:
string  = "Rupesh";  % semi colon can be used for storing the data and not printing it

disp(string)

Rupesh


In [5]:
disp(sprintf("hello world it's %s", "Rupesh"))

# disp is used to diplay and varible

disp(sprintf("pi value is  %0.2f", pi))

# if you are familiar to c for priting the c format printf we can use sprintf for c type printing

hello world it's Rupesh
pi value is  3.14


you can use both # and % for commenting

# Matrixs and vectors

In [6]:
row = [1 2 3 4 5] % row vector 1 X 5
col = [1; 2; 3; 4; 5] %column vector 5 X 1

# dot prodct 
row * col % method 1 ( or ) 

dot(row, col) % resulting is 1 X 1

# for element wise matrix or vector operation use . before the operator
row .*col %element wise multiplication

row =

   1   2   3   4   5

col =

   1
   2
   3
   4
   5

ans =  55
ans =  55
ans =

    1    2    3    4    5
    2    4    6    8   10
    3    6    9   12   15
    4    8   12   16   20
    5   10   15   20   25



In [7]:
mat = [1 2; 3 4; 5 6] %matrix

concat = [1 ; 3; 4] 

concatinated = [mat concat] %concatinating the matrix

mat =

   1   2
   3   4
   5   6

concat =

   1
   3
   4

concatinated =

   1   2   1
   3   4   3
   5   6   4



In [8]:
concatinated(:) %returns a vertically stacked mat elemets

ans =

   1
   3
   5
   2
   4
   6
   1
   3
   4



In [9]:
# indexing
concatinated(1, :) %returns first row all the cols
concatinated([1, 3], 1) %return elemets of 1, 3 rows with first col

ans =

   1   2   1

ans =

   1
   5



In [10]:
eye(3) %identity matrix of n dimenstion

ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1



In [11]:
A = [1 2; 3 4]
log(A)
exp(A)
pinv(A) % inverse of A (sudo inverse)

% sudo inverse just means if the matrix is not invertable it does the pusdo inverse

A =

   1   2
   3   4

ans =

   0.00000   0.69315
   1.09861   1.38629

ans =

    2.7183    7.3891
   20.0855   54.5982

ans =

  -2.00000   1.00000
   1.50000  -0.50000



In [12]:
A > 3 % return boolean

ans =

  0  0
  0  1



In [13]:
sum(A) %gives col wise sum
prod(A) %col wise product
prod(prod(A))
A' % transpose

ans =

   4   6

ans =

   3   8

ans =  24
ans =

   1   3
   2   4



In [14]:
ones(2, 3) % specify the shape of the required size of matrix

ans =

   1   1   1
   1   1   1



In [15]:
rand(2, 2) % from random distribution

ans =

   0.25225   0.78393
   0.19142   0.78164



In [16]:
randn(4, 5) % draws random variables from a gaussian distrubtion

ans =

   0.726179   2.188585   1.600255  -0.656342  -0.139739
   0.533793   1.597031   0.492434   0.121239   0.064225
   0.490981  -0.758961   0.158406  -1.625175  -1.130059
   0.871611   0.476823  -1.659190  -0.850076  -0.405484



In [39]:
% simple plot to show what a gaussian distribution is 

gauss = randn(1, 2000);
hist(gauss, bins = 50, normed = true) % bins is a parameter for chosing no. of bins
legend('Rupi' )
xlabel("normal distribution")


# Loading the data

In [18]:
A = [1 2; 3 4; 5 6]

size(A) %size itself is a vector

size(size(A))

A =

   1   2
   3   4
   5   6

ans =

   3   2

ans =

   1   2



In [19]:
length(A) % returns the highest dimension

ans =  3


In [20]:
# lading the data is simple a one line command in Octave
# get to required directory and type command
load house.csv

%or load('house.csv')
% and who command shows all variables in the environment

error: load: unable to find file house.csv


# Control Statements

In [21]:
# for loop
v = ones(10, 1)


for i = 1:10,
    v(i) = 2^i;
end;
disp(v)

v =

   1
   1
   1
   1
   1
   1
   1
   1
   1
   1

      2
      4
      8
     16
     32
     64
    128
    256
    512
   1024


In [22]:
% While
i = 1;

while i < 10 ,
    v(i) = v(i) *i;
    i += 1;
end;
v

v =

      2
      8
     24
     64
    160
    384
    896
   2048
   4608
   1024



In [23]:
# if Else

i = 10

if(i == 10),
    disp("True");
else,
    disp("False");
end;



i =  10
True


for functions you need to save them in .m file

function need a .m file for it search in path 

functions in octave can have more than one return value

In [24]:
function [a, b] = square(x)
    a = x ^2;
    b = x ^3;
    
# you have save this in .m format and run 


# Thank You !
that's all there is to it,this much should be enough for you to implement machine learning algorithms